name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
